const S=window.STUDY,g=S.gradient,layer=document.querySelector('#layer');const X=x=>75+x*.75,Y=y=>545-y*.6;
document.querySelector('#metrics').innerHTML=`<div class="metric"><strong>3</strong><span>Simultaneous synthetic heads</span></div><div class="metric"><strong>${g.gradient_m_per_m.toFixed(5)}</strong><span>Hydraulic gradient (m/m)</span></div><div class="metric"><strong>${g.flow_bearing_deg.toFixed(1)}°</strong><span>Down-gradient bearing, clockwise from north</span></div>`;
function render(){let p=['<defs><clipPath id="boundary"><rect x="75" y="65" width="750" height="480"/></clipPath><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L9 3L0 6Z" fill="#173c3b"/></marker></defs><rect x="75" y="65" width="750" height="480" fill="#edf0e7"/>'];
if(layer.value!=='head')S.units.forEach(u=>p.push(`<polygon points="${u.polygon.map(v=>`${X(v[0])},${Y(v[1])}`).join(' ')}" fill="${u.color}"/>`));
if(layer.value!=='geology'){p.push('<g clip-path="url(#boundary)">');for(let h=97;h<=99;h+=.5){let ya=(h-g.intercept_m)/g.dh_dy,yb=(h-g.intercept_m-g.dh_dx*1000)/g.dh_dy;p.push(`<path d="M${X(0)} ${Y(ya)}L${X(1000)} ${Y(yb)}" stroke="#377969" stroke-width="2" stroke-dasharray="6 5"/>`);let yy=380,xx=(h-g.intercept_m-g.dh_dy*yy)/g.dh_dx;if(xx>0&&xx<1000)p.push(`<text x="${X(xx)+8}" y="${Y(yy)}">${h.toFixed(1)} m</text>`)}p.push('</g>');const x=390,y=310,scale=90000;p.push(`<path d="M${X(x)} ${Y(y)}L${X(x-g.dh_dx*scale)} ${Y(y-g.dh_dy*scale)}" stroke="#173c3b" stroke-width="4" marker-end="url(#arrow)"/><text x="${X(x)-20}" y="${Y(y)+28}">Down-gradient</text>`)}
p.push(`<polygon points="${S.wells.map(w=>`${X(w.x)},${Y(w.y)}`).join(' ')}" fill="none" stroke="#708275" stroke-dasharray="2 6"/>`);
S.wells.forEach(w=>p.push(`<circle cx="${X(w.x)}" cy="${Y(w.y)}" r="9" fill="#173c3b" stroke="#fffdf7" stroke-width="3"><title>${w.id}: ${w.head_m} m</title></circle><text x="${X(w.x)+15}" y="${Y(w.y)-16}">${w.id}</text><text x="${X(w.x)+15}" y="${Y(w.y)+3}">${w.head_m.toFixed(2)} m</text>`));
for(let x=0;x<=1000;x+=200)p.push(`<text x="${X(x)}" y="570" text-anchor="middle">${x}</text>`);for(let y=0;y<=800;y+=200)p.push(`<text x="60" y="${Y(y)+5}" text-anchor="end">${y}</text>`);
p.push('<text x="410" y="607">Easting (m)</text><text x="10" y="35">Northing (m)</text><path d="M865 110V60" stroke="#173c3b" stroke-width="2" marker-end="url(#arrow)"/><text x="860" y="45">N</text>');document.querySelector('#map').innerHTML=p.join('');}
function selectWell(id){const w=S.wells.find(w=>w.id===id);document.querySelector('#well-detail').textContent=`${w.id} · Local position: ${w.x} m east, ${w.y} m north · Head: ${w.head_m.toFixed(2)} m above the shared local datum · Screened aquifer: ${w.unit}.`;document.querySelectorAll('.well-btn').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===id)))}
S.wells.forEach(w=>{const b=document.createElement('button');b.type='button';b.className='well-btn secondary';b.textContent=w.id;b.addEventListener('click',()=>selectWell(w.id));document.querySelector('#well-buttons').append(b)});layer.addEventListener('change',render);render();selectWell('MW-01');
