import {spawn} from 'node:child_process';import fs from 'node:fs';import assert from 'node:assert/strict';
import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import lighthouse from 'lighthouse';
const base='http://127.0.0.1:4321/projects/acqua-in-chiaro/';fs.mkdirSync('qa-results',{recursive:true});
const report={started:new Date().toISOString(),browser:'not run',flows:[],visual:[],axe:[],lighthouse:[],errors:[]};
const server=spawn(process.execPath,['node_modules/astro/astro.js','preview','--host','127.0.0.1','--port','4321'],{stdio:'pipe'});let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));if(i===99)throw Error('Preview server unavailable');}
 browser=await chromium.launch({headless:true,args:['--remote-debugging-port=9222']});report.browser='executed';
 const context=await browser.newContext({viewport:{width:360,height:800},isMobile:true,hasTouch:true});
 const page=await context.newPage();const runtimeErrors=[],external=[];page.on('pageerror',e=>runtimeErrors.push(String(e)));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4321/')&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.goto(base);await page.getByRole('searchbox').fill('Levissima');await page.getByRole('button',{name:'Cerca →'}).click();await page.getByRole('heading',{name:'Levissima',exact:true}).waitFor();await page.getByRole('heading',{name:'Levissima',exact:true}).getByRole('link').click();await page.getByRole('heading',{name:'Da dove vengono questi numeri'}).waitFor();assert.ok(await page.getByText('2023-09-04',{exact:true}).count());await page.getByRole('button',{name:'＋ Confronta',exact:true}).click();await page.getByRole('link',{name:'Apri il confronto →'}).waitFor();report.flows.push('B: search → detail → provenance → selection');
 await page.goto(base+'acque/?f=sodio');await page.getByRole('button',{name:'Filtri chimici (1)'}).waitFor();await page.getByRole('button',{name:'Filtri chimici (1)'}).click();assert.equal(await page.getByRole('checkbox',{name:'Sodio < 20 mg/L'}).isChecked(),true);assert.equal(await page.getByRole('heading',{name:'Uliveto',exact:true}).count(),0);await page.getByRole('button',{name:'Azzera filtri',exact:true}).click();await page.getByRole('heading',{name:'Uliveto',exact:true}).waitFor();report.flows.push('A: URL chemistry filter → matching cards → reset');
 await page.goto(base+'confronta/?ids=levissima,acqua-panna');await page.getByRole('button',{name:'Rimuovi Levissima'}).waitFor();await page.getByLabel('Aggiungi una scheda').selectOption('milano-18-2026-07');await page.getByRole('button',{name:'Aggiungi',exact:true}).click();await page.getByRole('button',{name:'Rimuovi Milano · Nord-Est · Luglio 2026'}).waitFor();assert.ok(page.url().includes('milano-18-2026-07'));await page.reload();await page.getByRole('button',{name:'Rimuovi Milano · Nord-Est · Luglio 2026'}).waitFor();assert.ok(await page.getByText('435',{exact:true}).count());await page.getByRole('button',{name:'Rimuovi Acqua Panna'}).click();assert.equal(await page.getByRole('button',{name:'Rimuovi Acqua Panna'}).count(),0);report.flows.push('C: two waters + Milano → shareable URL → reload → remove');
 await page.goto(base+'rubinetto/milano/');await page.getByLabel('Zona').selectOption('Sud-Ovest');await page.getByLabel('Periodo').selectOption('2026-01');await page.getByRole('heading',{name:'Milano · Sud-Ovest · Gennaio 2026'}).waitFor();report.flows.push('Milano: zone and period change');
 for(const width of [360,768,1280])for(const colorScheme of ['light','dark']){await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});for(const [name,url] of [['home',''],['catalogue','acque/?f=sodio'],['detail','acque/levissima/'],['compare','confronta/?ids=levissima,acqua-panna,milano-18-2026-07'],['milano','rubinetto/milano/'],['guide','profili/stitichezza/']]){await page.goto(base+url);await page.waitForLoadState('networkidle');await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name} overflow ${width}`);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.axe.push({name,width,colorScheme,violations:result.violations});assert.equal(result.violations.length,0,`${name}: axe ${result.violations.map(v=>v.id)}`);const file=`qa-results/${name}-${width}-${colorScheme}.png`;await page.screenshot({path:file,fullPage:true});report.visual.push(file);}}
 assert.deepEqual(runtimeErrors,[],'Browser runtime errors');assert.deepEqual(external,[],'Third-party network requests');
 for(const route of ['','acque/levissima/','confronta/','rubinetto/milano/']){const result=await lighthouse(base+route,{port:9222,output:'json',onlyCategories:['performance','accessibility','best-practices','seo'],logLevel:'error'});const scores=Object.fromEntries(Object.entries(result.lhr.categories).map(([k,v])=>[k,v.score]));report.lighthouse.push({route,scores});fs.writeFileSync('qa-results/lighthouse-'+(route.replaceAll('/','-')||'home')+'.json',result.report);assert.ok(scores.accessibility>=.95&&scores.performance>=.9&&scores.seo>=.9,'Lighthouse targets');}
 report.status='automated checks passed; manual screenshot review still required';
}catch(e){report.errors.push(String(e));report.status='failed or unavailable';process.exitCode=1;console.error(e);}
finally{if(browser)await browser.close();server.kill();fs.writeFileSync('qa-results/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,browser:report.browser,flows:report.flows,screenshots:report.visual.length,errors:report.errors}));}
