const data=window.STUDY, analyte=document.querySelector('#analyte'), limit=document.querySelector('#limit');const defaults={nitrate:50,chloride:250,benzene:1};
function classify(v,q,t){return q==='<'?(v<=t?'Below reference (non-detect)':'Indeterminate'):(v>t?'Above reference':'At or below reference')}
function render(){const t=Number(limit.value);if(!Number.isFinite(t)||t<=0){document.querySelector('#error').textContent='Enter a positive reference value. The chart below retains the last valid comparison.';return}document.querySelector('#error').textContent='';const rows=data.filter(r=>r.analyte===analyte.value).map(r=>({...r,status:classify(r.value,r.qualifier,t)}));
const above=rows.filter(r=>r.status==='Above reference').length,unknown=rows.filter(r=>r.status==='Indeterminate').length;
document.querySelector('#metrics').innerHTML=`<div class="metric"><strong>${rows.length}</strong><span>Samples · 15 Sep 2025</span></div><div class="metric"><strong>${above}</strong><span>Confirmed above reference</span></div><div class="metric"><strong>${unknown}</strong><span>Indeterminate comparisons</span></div>`;
const unit=rows[0].unit,max=Math.max(t,...rows.map(r=>r.value))*1.3,y=v=>250-v/max*205;let p=[`<text x="30" y="22">${analyte.value} (${unit})</text><path d="M65 250H855" stroke="#83978b"/>`];
rows.forEach((r,i)=>{const x=140+i*250;const color=r.status==='Above reference'?'#b27138':r.status==='Indeterminate'?'#8975a4':'#307666';p.push(`<rect x="${x}" y="${y(r.value)}" width="95" height="${250-y(r.value)}" fill="${r.qualifier==='<'?'none':color}" stroke="${color}" stroke-width="3" ${r.qualifier==='<'?'stroke-dasharray="5 4"':''}/><text x="${x+47}" y="${y(r.value)-12}" text-anchor="middle">${r.qualifier==='<'?'&lt; ':''}${r.value}</text><text x="${x+47}" y="280" text-anchor="middle">${r.well}</text>`)});p.push(`<path d="M65 ${y(t)}H855" stroke="#975128" stroke-width="2" stroke-dasharray="7 5"/><text x="850" y="${y(t)-10}" text-anchor="end">Reference: ${t} ${unit}</text>`);document.querySelector('#chart').innerHTML=p.join('');
document.querySelector('#rows').innerHTML=rows.map(r=>`<tr><td>${r.well}</td><td>${r.qualifier==='<'?'&lt; ':''}${r.value} ${unit}</td><td>${t} ${unit}</td><td><span class="pill ${r.status==='Above reference'?'flag':r.status==='Indeterminate'?'unknown':''}">${r.status}</span></td></tr>`).join('');}
analyte.addEventListener('change',()=>{limit.value=defaults[analyte.value];render()});limit.addEventListener('input',render);document.querySelector('#reset').addEventListener('click',()=>{limit.value=defaults[analyte.value];render()});render();
